services: 
  pytorch-gpu:
    image: "missgod1/pytorch:1.9.0-cuda11.1-cudnn8-runtime"
    environment:
      - USERNAME=
      - PASSWORD=
    ports: 
      - '22'
    # volumes:
    #   - ./code:/workspace
    runtime: "nvidia"