version: '3.9'
services: 
  gpu:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - '2222:22'
      - '8888:8888'
    volumes:
      - ./code:/workspace
    runtime: "nvidia"
  cpu:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - '2222:22'
      - '8888:8888'
    volumes:
      - ./code:/workspace