services:
  potrainer:
    image: "cr.portainer.io/portainer/portainer-ce:2.9.3"
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data: